"""Document upload validation and orchestration.

The server never trusts the client for size, MIME type or storage key: the body
is read in bounded chunks, the SHA-256 and the size are computed locally, the
format comes from magic bytes and the key is generated by the API. The object
is written to private storage before the active metadata row exists, and a
failed metadata write compensates the object.
"""

from __future__ import annotations

import hashlib
import uuid
from collections.abc import AsyncIterator, Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
from tempfile import SpooledTemporaryFile
from typing import BinaryIO, Final, cast
from urllib.parse import quote
from uuid import UUID

from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from starlette.datastructures import UploadFile

from app.clinics.audit import ClinicAuditService
from app.clinics.rbac import Permission, Role, require_permission, role_allows
from app.core.clock import utcnow
from app.core.context import TenantContext
from app.core.errors import (
    InvalidInputError,
    NotFoundError,
    PayloadTooLargeError,
    PermissionDeniedError,
    StorageUnavailableError,
    UnsupportedMediaTypeError,
    translate_integrity_error,
)
from app.core.tenancy import tenant_transaction
from app.documents.models import PatientDocument
from app.documents.repositories import DocumentRepository
from app.documents.schemas import (
    FILENAME_MAX_LENGTH,
    DocumentCategory,
    DocumentListParams,
    DocumentStatus,
)
from app.patients.repositories.patient_repository import PatientRepository
from app.platform.logging import get_logger
from app.platform.storage import ObjectStorage

MAX_DOCUMENT_BYTES: Final[int] = 10 * 1024 * 1024
UPLOAD_CHUNK_BYTES: Final[int] = 1024 * 1024
SIGNATURE_BYTES: Final[int] = 8

MIME_SIGNATURES: Final[tuple[tuple[str, bytes], ...]] = (
    ("application/pdf", b"%PDF-"),
    ("image/jpeg", b"\xff\xd8\xff"),
    ("image/png", b"\x89PNG\r\n\x1a\n"),
)

CATEGORY_PERMISSIONS: Final[Mapping[DocumentCategory, tuple[Permission, Permission]]] = {
    DocumentCategory.ADMINISTRATIVE: (
        Permission.DOCUMENTS_ADMINISTRATIVE_READ,
        Permission.DOCUMENTS_ADMINISTRATIVE_MANAGE,
    ),
    DocumentCategory.CLINICAL: (
        Permission.DOCUMENTS_CLINICAL_READ,
        Permission.DOCUMENTS_CLINICAL_MANAGE,
    ),
}

_logger = get_logger()


def detect_document_mime(head: bytes) -> str | None:
    """Return the accepted MIME type matching ``head``, or ``None``."""

    for mime, signature in MIME_SIGNATURES:
        if head.startswith(signature):
            return mime
    return None


def document_read_permission(category: DocumentCategory) -> Permission:
    return CATEGORY_PERMISSIONS[category][0]


def document_manage_permission(category: DocumentCategory) -> Permission:
    return CATEGORY_PERMISSIONS[category][1]


def readable_categories(role: Role) -> frozenset[DocumentCategory]:
    """Categories the role may list, filter and read metadata from."""

    return frozenset(
        category
        for category, (read_permission, _) in CATEGORY_PERMISSIONS.items()
        if role_allows(role, read_permission)
    )


def sanitize_filename(filename: str | None) -> str:
    """Keep a display-only basename, never a path, control or quote character."""

    basename = (filename or "").replace("\\", "/").rsplit("/", maxsplit=1)[-1]
    printable = "".join(
        character for character in basename if character.isprintable() and character not in '"\r\n'
    ).strip()
    return printable[:FILENAME_MAX_LENGTH] or "documento"


def content_disposition(filename: str) -> str:
    """Build an attachment header with ASCII fallback and RFC 5987 encoding."""

    fallback = "".join(
        character if character.isascii() and (character.isalnum() or character in "._-") else "_"
        for character in filename
    ).strip("_")
    return (
        f'attachment; filename="{fallback or "documento"}"; '
        f"filename*=UTF-8''{quote(filename, safe='')}"
    )


@dataclass(frozen=True, slots=True)
class StagedDocument:
    """A validated upload spooled in memory with its server-side facts."""

    file_object: BinaryIO
    mime: str
    size_bytes: int
    sha256: str


async def stage_document(upload: UploadFile) -> StagedDocument:
    """Read the upload in chunks, enforcing the format and size contract.

    The returned spool is positioned at the start and owned by the caller, who
    must close it. Oversized or unsupported bodies raise before any storage or
    database write happens.
    """

    hasher = hashlib.sha256()
    spool: SpooledTemporaryFile[bytes] = SpooledTemporaryFile(max_size=UPLOAD_CHUNK_BYTES)
    size_bytes = 0
    head = b""
    try:
        while True:
            chunk = await upload.read(UPLOAD_CHUNK_BYTES)
            if not chunk:
                break
            size_bytes += len(chunk)
            if size_bytes > MAX_DOCUMENT_BYTES:
                raise PayloadTooLargeError("document exceeds the size limit")
            if len(head) < SIGNATURE_BYTES:
                head += chunk[: SIGNATURE_BYTES - len(head)]
            hasher.update(chunk)
            spool.write(chunk)

        if size_bytes == 0:
            raise UnsupportedMediaTypeError("document is empty")
        mime = detect_document_mime(head)
        if mime is None:
            raise UnsupportedMediaTypeError("document type is not supported")

        spool.seek(0)
        return StagedDocument(
            file_object=cast(BinaryIO, spool),
            mime=mime,
            size_bytes=size_bytes,
            sha256=hasher.hexdigest(),
        )
    except BaseException:
        spool.close()
        raise


@dataclass(frozen=True, slots=True)
class DocumentPage:
    items: Sequence[PatientDocument]
    total: int


@dataclass(frozen=True, slots=True)
class DocumentContent:
    document: PatientDocument
    chunks: AsyncIterator[bytes]


def _generate_key() -> str:
    return uuid.uuid4().hex


def _clean_title(title: str) -> str:
    cleaned = title.strip()
    if not cleaned:
        raise InvalidInputError("title cannot be blank")
    return cleaned


class DocumentService:
    """Orchestrates private documents of one patient."""

    def __init__(
        self,
        session_factory: async_sessionmaker[AsyncSession],
        storage: ObjectStorage,
        *,
        clock: Callable[[], datetime] = utcnow,
        key_factory: Callable[[], str] = _generate_key,
    ) -> None:
        self._session_factory = session_factory
        self._storage = storage
        self._clock = clock
        self._key_factory = key_factory

    async def list_documents(
        self,
        context: TenantContext,
        role: Role,
        patient_id: UUID,
        params: DocumentListParams,
    ) -> DocumentPage:
        categories = readable_categories(role)
        if not categories:
            raise PermissionDeniedError("role cannot read documents")
        if params.category is not None:
            if params.category not in categories:
                raise PermissionDeniedError("role cannot read this document category")
            categories = frozenset({params.category})

        async with tenant_transaction(self._session_factory, context) as session:
            await self._require_patient(session, context, patient_id)
            items, total = await DocumentRepository(session).list(
                context,
                patient_id,
                categories=frozenset(category.value for category in categories),
                status=params.status,
                limit=params.limit,
                offset=params.offset,
            )
        return DocumentPage(items=items, total=total)

    async def get_document(
        self, context: TenantContext, role: Role, patient_id: UUID, document_id: UUID
    ) -> PatientDocument:
        document = await self._get_document(context, patient_id, document_id)
        category = DocumentCategory(document.category)
        require_permission(role, document_read_permission(category))
        return document

    async def open_content(
        self, context: TenantContext, role: Role, patient_id: UUID, document_id: UUID
    ) -> DocumentContent:
        """Authorize by metadata first; only then touch the storage backend."""

        document = await self.get_document(context, role, patient_id, document_id)
        chunks = await self._storage.stream(document.storage_key)
        return DocumentContent(document=document, chunks=chunks)

    async def upload_document(
        self,
        context: TenantContext,
        role: Role,
        patient_id: UUID,
        *,
        category: DocumentCategory,
        title: str,
        upload: UploadFile,
    ) -> PatientDocument:
        require_permission(role, document_manage_permission(category))
        cleaned_title = _clean_title(title)
        await self._require_patient_in_transaction(context, patient_id)

        staged = await stage_document(upload)
        key = self._key_factory()
        try:
            await self._storage.put(key, staged.file_object, content_type=staged.mime)
        finally:
            staged.file_object.close()

        try:
            async with tenant_transaction(self._session_factory, context) as session:
                try:
                    document = await DocumentRepository(session).add(
                        context,
                        patient_id,
                        category=category.value,
                        title=cleaned_title,
                        original_filename=sanitize_filename(upload.filename),
                        detected_mime=staged.mime,
                        size_bytes=staged.size_bytes,
                        sha256=staged.sha256,
                        storage_key=key,
                        uploaded_by_user_id=context.user_id,
                    )
                except IntegrityError as error:
                    raise translate_integrity_error(error) from error
                await ClinicAuditService(session).record(
                    "document.created",
                    clinic_id=context.clinic_id,
                    actor_user_id=context.user_id,
                    entity_type="patient_document",
                    entity_id=document.id,
                    metadata={
                        "patient_id": str(patient_id),
                        "category": document.category,
                        "status": document.status,
                    },
                )
        except BaseException:
            await self._compensate(key, context)
            raise
        return document

    async def set_archived(
        self,
        context: TenantContext,
        role: Role,
        patient_id: UUID,
        document_id: UUID,
        *,
        archived: bool,
    ) -> PatientDocument:
        target = DocumentStatus.ARCHIVED if archived else DocumentStatus.ACTIVE
        async with tenant_transaction(self._session_factory, context) as session:
            repository = DocumentRepository(session)
            document = await repository.get(context, patient_id, document_id)
            if document is None:
                raise NotFoundError("document not found")
            category = DocumentCategory(document.category)
            require_permission(role, document_manage_permission(category))
            if document.status == target.value:
                return document

            now = self._clock()
            updated = await repository.update_status(
                context,
                patient_id,
                document_id,
                status=target.value,
                archived_at=now if archived else None,
                updated_at=now,
            )
            if updated is None:
                raise NotFoundError("document not found")
            event_type = "document.archived" if archived else "document.restored"
            await ClinicAuditService(session).record(
                event_type,
                clinic_id=context.clinic_id,
                actor_user_id=context.user_id,
                entity_type="patient_document",
                entity_id=updated.id,
                metadata={
                    "patient_id": str(patient_id),
                    "category": updated.category,
                    "status": updated.status,
                },
            )
        return updated

    async def _get_document(
        self, context: TenantContext, patient_id: UUID, document_id: UUID
    ) -> PatientDocument:
        async with tenant_transaction(self._session_factory, context) as session:
            document = await DocumentRepository(session).get(context, patient_id, document_id)
        if document is None:
            raise NotFoundError("document not found")
        return document

    async def _require_patient_in_transaction(
        self, context: TenantContext, patient_id: UUID
    ) -> None:
        async with tenant_transaction(self._session_factory, context) as session:
            await self._require_patient(session, context, patient_id)

    async def _require_patient(
        self, session: AsyncSession, context: TenantContext, patient_id: UUID
    ) -> None:
        patient = await PatientRepository(session).get(context, patient_id)
        if patient is None:
            raise NotFoundError("patient not found")

    async def _compensate(self, key: str, context: TenantContext) -> None:
        """Best-effort removal of an object whose metadata write failed.

        A failed compensation becomes an operational event without document
        content so reconciliation can find the orphaned object.
        """

        try:
            await self._storage.delete(key)
        except StorageUnavailableError:
            _logger.error(
                "document.storage_compensation_failed",
                extra={
                    "context": {
                        "clinic_id": str(context.clinic_id),
                        "user_id": str(context.user_id),
                    }
                },
            )
